// GENERATED by @edgedb/generate v0.4.1

import type {Executor} from "edgedb";


export type GetMovieReturns = {
  "title": string;
  "actors": {
    "name": string;
  }[];
} | null;

export async function getMovie(client: Executor): Promise<GetMovieReturns> {
  return client.querySingle(`\
select Movie {
      title,
      actors: {
        name,
      }
} filter .title = "Iron Man 2"`);

}
